### ISSUE TITLE
性別情報の更新/確認を行いたい

### ISSUE THREAD

**Issue by Shimiiy** [SIT-DigiCre/digicore_v3_frontend#56]
**9/11　新入部員のデジコアへの登録失敗のトラブル対応で発覚**

バックエンド側から性別の登録を要求されているが、
**フロントエンド側で性別を登録する欄が存在しないので進めない。**
https://github.com/SIT-DigiCre/digicore_v3_frontend/blob/master/components/Profile/PrivateProfileEditor.tsx

**Comment by Shimiiy** [comment]
件の新入部員は、 _18th えくと_ が手動で直接 DB に個人情報を登録することで対応したが、
似たような状態に陥っている方がおそらく何人もいる

**Comment by ecto0310** [comment]
> フロントエンド側で性別を登録する欄が存在しないので進めない。
これは嘘で、進めなかった原因はAPIとDBカラムの不整合が原因であることが分かった。
なので、更新は問題無く動作する。(だが、どちらにしろ性別情報は欲しいのでPOSTデータの更新は欲しい。

**Comment by Shimiiy** [comment]
登録フローの再実装 #78 で更新・確認できるようになった
