### ISSUE TITLE
Workアイテムを全て読込むため、Work一覧の処理が重くなる

### ISSUE THREAD

**Issue by Shimiiy** [SIT-DigiCre/digicore_v3_frontend#87]
![Image Pasted at 2023-4-17 16-34](https://user-images.githubusercontent.com/64347376/232418870-5b767f9d-42d3-46a4-86ee-cb8d050410f7.png)

**Comment by MogamiTsuchikawa** [comment]
こちら、殆どスライドが原因だと思われるのでスライドの表示を1アクション増やしてみるとよいかも
